# Generated by Django 5.2.6 on 2025-11-01 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compras',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('empresa_id', models.IntegerField()),
                ('proveedor_nombre', models.CharField(max_length=150)),
                ('proveedor_nit', models.CharField(max_length=50)),
                ('fecha', models.DateField()),
                ('almacen_id', models.IntegerField()),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('CONFIRMADA', 'Confirmada'), ('ANULADA', 'Anulada')], default='BORRADOR', max_length=12)),
                ('total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('creado_por', models.IntegerField()),
                ('creado_en', models.DateTimeField()),
                ('trial102', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'compra',
                'ordering': ['-fecha', '-id'],
                'managed': False,
            },
        ),
    ]
