# Generated by Django 5.2.6 on 2025-10-17 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('empresa_id', models.IntegerField(db_column='empresa_id')),
                ('sku', models.CharField(max_length=64)),
                ('nombre', models.CharField(max_length=150)),
                ('unidad', models.CharField(max_length=10)),
                ('metodo_costo', models.CharField(max_length=20)),
                ('costo_promedio', models.DecimalField(decimal_places=2, max_digits=12)),
                ('precio_detal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('precio_mayor', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('umbral_mayor', models.IntegerField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'producto',
                'managed': False,
            },
        ),
    ]
