# Generated by Django 5.2.6 on 2025-09-30 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Almacen',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=80)),
                ('ubicacion', models.CharField(blank=True, max_length=120, null=True)),
                ('trial102', models.SmallIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'almacen',
                'managed': False,
            },
        ),
    ]
